package com.eclinic.db.model;

// Generated 2015-05-03 18:58:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Address generated by hbm2java
 */
@Entity
@Table(name = "Address")
public class Address implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String city;
	private String countryCode;
	private String province;
	private String country;
	private String countryCodeCity;
	private String homeNr;
	private Set<Patient> patients = new HashSet<Patient>(0);

	public Address() {
	}

	public Address(String city, String countryCode, String province,
			String country, String countryCodeCity) {
		this.city = city;
		this.countryCode = countryCode;
		this.province = province;
		this.country = country;
		this.countryCodeCity = countryCodeCity;
	}

	public Address(String city, String countryCode, String province,
			String country, String countryCodeCity, String homeNr, Set<Patient> patients) {
		this.city = city;
		this.countryCode = countryCode;
		this.province = province;
		this.country = country;
		this.countryCodeCity = countryCodeCity;
		this.homeNr = homeNr;
		this.patients = patients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "city", nullable = false, length = 10)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "country_code", nullable = false, length = 10)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "province", nullable = false, length = 20)
	public String getProvince() {
		return this.province;
	}

	public void setProvince(String province) {
		this.province = province;
	}

	@Column(name = "country", nullable = false, length = 20)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "country_code_city", nullable = false, length = 20)
	public String getCountryCodeCity() {
		return this.countryCodeCity;
	}

	public void setCountryCodeCity(String countryCodeCity) {
		this.countryCodeCity = countryCodeCity;
	}

	@Column(name = "home_nr", length = 20)
	public String getHomeNr() {
		return this.homeNr;
	}

	public void setHomeNr(String homeNr) {
		this.homeNr = homeNr;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Patient> getPatients() {
		return this.patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

}
