package com.eclinic.db.model;

// Generated 2015-05-03 18:58:02 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ApplicationParameter generated by hbm2java
 */
@Entity
@Table(name = "Application_Parameter", catalog = "eclinic")
public class ApplicationParameter implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private String key;
	private String valueString;
	private int valueNumber;

	public ApplicationParameter() {
	}

	public ApplicationParameter(String key, String valueString, int valueNumber) {
		this.key = key;
		this.valueString = valueString;
		this.valueNumber = valueNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "key", nullable = false, length = 20)
	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@Column(name = "value_string", nullable = false, length = 50)
	public String getValueString() {
		return this.valueString;
	}

	public void setValueString(String valueString) {
		this.valueString = valueString;
	}

	@Column(name = "value_number", nullable = false)
	public int getValueNumber() {
		return this.valueNumber;
	}

	public void setValueNumber(int valueNumber) {
		this.valueNumber = valueNumber;
	}

}
