package com.eclinic.db.model;

// Generated 2015-05-03 18:58:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LoginHistory generated by hbm2java
 */
@Entity
@Table(name = "Login_History")
public class LoginHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
	private Worker worker;
	private Date dateLogin;
	private String sessionNumber;
	private Date dateLogout;

	public LoginHistory() {
	}

	public LoginHistory(Worker worker, Date dateLogin, String sessionNumber,
			Date dateLogout) {
		this.worker = worker;
		this.dateLogin = dateLogin;
		this.sessionNumber = sessionNumber;
		this.dateLogout = dateLogout;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_worker", nullable = false)
	public Worker getWorker() {
		return this.worker;
	}

	public void setWorker(Worker worker) {
		this.worker = worker;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_login", nullable = false, length = 10)
	public Date getDateLogin() {
		return this.dateLogin;
	}

	public void setDateLogin(Date dateLogin) {
		this.dateLogin = dateLogin;
	}

	@Column(name = "session_number", nullable = false, length = 50)
	public String getSessionNumber() {
		return this.sessionNumber;
	}

	public void setSessionNumber(String sessionNumber) {
		this.sessionNumber = sessionNumber;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_logout", nullable = false, length = 10)
	public Date getDateLogout() {
		return this.dateLogout;
	}

	public void setDateLogout(Date dateLogout) {
		this.dateLogout = dateLogout;
	}

}
