package com.eclinic.db.model;

// Generated 2015-05-03 18:58:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Report generated by hbm2java
 */
@Entity
@Table(name = "Report", catalog = "eclinic")
public class Report implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -462788684445991633L;
	private Long id;
	private Date dateFrom;
	private Date dateTo;
	private String description;
	private byte[] reportData;

	public Report() {
	}

	public Report(Date dateFrom, byte[] reportData) {
		this.dateFrom = dateFrom;
		this.reportData = reportData;
	}

	public Report(Date dateFrom, Date dateTo, String description,
			byte[] reportData) {
		this.dateFrom = dateFrom;
		this.dateTo = dateTo;
		this.description = description;
		this.reportData = reportData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_from", nullable = false, length = 10)
	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_to", length = 10)
	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "report_data", nullable = false)
	public byte[] getReportData() {
		return this.reportData;
	}

	public void setReportData(byte[] reportData) {
		this.reportData = reportData;
	}

}
