package com.eclinic.db.model;

// Generated 2015-05-03 18:58:02 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SpecalVisitField generated by hbm2java
 */
@Entity
@Table(name = "Specal_Visit_Field")
public class SpecalVisitField implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7717347136813341475L;
	private Long id;
	private Specialization specialization;
	private String name;
	private String value;
	private String typeOfValue;

	public SpecalVisitField() {
	}

	public SpecalVisitField(Specialization specialization, String name,
			String typeOfValue) {
		this.specialization = specialization;
		this.name = name;
		this.typeOfValue = typeOfValue;
	}

	public SpecalVisitField(Specialization specialization, String name,
			String value, String typeOfValue) {
		this.specialization = specialization;
		this.name = name;
		this.value = value;
		this.typeOfValue = typeOfValue;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_specialization", nullable = false)
	public Specialization getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Specialization specialization) {
		this.specialization = specialization;
	}

	@Column(name = "name", nullable = false, length = 40)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", length = 40)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "type_of_value", nullable = false, length = 40)
	public String getTypeOfValue() {
		return this.typeOfValue;
	}

	public void setTypeOfValue(String typeOfValue) {
		this.typeOfValue = typeOfValue;
	}

}
