package com.eclinic.db.model;

// Generated 2015-05-03 18:58:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VisitScheduler generated by hbm2java
 */
@Entity
@Table(name = "Visit_Scheduler")
public class VisitScheduler implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private Specialization specialization;
	private Doctor doctor;
	private int numberOfDay;
	private Integer numberOfMonth;
	private byte[] description;
	private Date timeOfVisit;

	public VisitScheduler() {
	}

	public VisitScheduler(long id, Specialization specialization,
			Doctor doctor, int numberOfDay) {
		this.id = id;
		this.specialization = specialization;
		this.doctor = doctor;
		this.numberOfDay = numberOfDay;
	}

	public VisitScheduler(long id, Specialization specialization,
			Doctor doctor, int numberOfDay, Integer numberOfMonth,
			byte[] description, Date timeOfVisit) {
		this.id = id;
		this.specialization = specialization;
		this.doctor = doctor;
		this.numberOfDay = numberOfDay;
		this.numberOfMonth = numberOfMonth;
		this.description = description;
		this.timeOfVisit = timeOfVisit;
	}

	@Id
	@Column(name = "Id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_specialization", nullable = false)
	public Specialization getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(Specialization specialization) {
		this.specialization = specialization;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_doctor", nullable = false)
	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	@Column(name = "number_of_day", nullable = false)
	public int getNumberOfDay() {
		return this.numberOfDay;
	}

	public void setNumberOfDay(int numberOfDay) {
		this.numberOfDay = numberOfDay;
	}

	@Column(name = "number_of_month")
	public Integer getNumberOfMonth() {
		return this.numberOfMonth;
	}

	public void setNumberOfMonth(Integer numberOfMonth) {
		this.numberOfMonth = numberOfMonth;
	}

	@Column(name = "description")
	public byte[] getDescription() {
		return this.description;
	}

	public void setDescription(byte[] description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "time_of_visit", length = 8)
	public Date getTimeOfVisit() {
		return this.timeOfVisit;
	}

	public void setTimeOfVisit(Date timeOfVisit) {
		this.timeOfVisit = timeOfVisit;
	}

}
